version: "3.9"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: ${PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}